name: qfinity
description: Qfinity is a comprehensive business Software solution created specially for the hospitality sector.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.4.3
  flutter: ^3.22.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  flutter_blurhash: ^0.8.2
  intl: ^0.19.0
  get: ^4.6.6
  dropdown_search: ^5.0.6
  syncfusion_flutter_core: ^26.2.5
  syncfusion_flutter_charts: ^26.2.5+1
  syncfusion_flutter_pdfviewer: ^26.2.5
  syncfusion_flutter_datagrid: ^26.2.5
  google_fonts: ^6.2.1
  dio: ^5.5.0+1
  flutter_phoenix: ^1.1.1
  flutter_easyloading: ^3.0.5
  font_awesome_flutter:
    path: ./packages/font_awesome_flutter
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  http_parser: ^4.1.0
  mime: ^1.0.5
  talker_dio_logger: ^4.3.4
  ansicolor: ^2.0.2
  logger: ^2.4.0
  flutter_fancy_tree_view: ^1.6.0
  responsive_framework: ^1.4.0
  auto_size_text: ^3.0.0
  pointycastle: ^3.9.1
  simple_animations: ^5.0.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1
  dependency_validator: ^4.1.0

dependency_overrides:
  collection: ^1.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/dummy/
    - assets/images/
    - assets/images/avatar/
    - assets/lang/
